name: Build and Deploy to ECS

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION:      ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID:  ${{ secrets.AWS_ACCOUNT_ID }}
  STATE_BUCKET:    ${{ secrets.STATE_BUCKET_NAME }}
  ECR_REPO:        ${{ secrets.ECR_REPO_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build image and deploy ECS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.8

      - name: Init Terraform (Infra - Phase 1)
        working-directory: environments/dev/phase1
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ env.STATE_BUCKET }}" \
            -backend-config="key=infra/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Apply Terraform (Infra - Phase 1)
        working-directory: environments/dev/phase1
        run: terraform apply -auto-approve

      - name: Get ECR Repository URL from Terraform Output
        id: get_ecr
        working-directory: environments/dev/phase1
        run: |
          echo "ECR_REPO_URL=$(terraform output -raw ecr_repository_url)" >> $GITHUB_ENV
          echo "ecr_repo_url=$(terraform output -raw ecr_repository_url)" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(date +%s)
          IMAGE_URI="${{ steps.get_ecr.outputs.ecr_repo_url }}:$IMAGE_TAG"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Init Terraform (ECS Service - Phase 2)
        working-directory: environments/dev/phase2
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ env.STATE_BUCKET }}" \
            -backend-config="key=ecs-service/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Plan ECS Service Update
        working-directory: environments/dev/phase2
        run: terraform plan -out=tfplan -var="image_url=${{ env.IMAGE_URI }}"

      - name: Apply ECS Service Update
        working-directory: environments/dev/phase2
        run: terraform apply -auto-approve tfplan
