name: Build and Deploy to ECS

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  AWS_REGION:      ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID:  ${{ secrets.AWS_ACCOUNT_ID }}
  STATE_BUCKET:    ${{ secrets.STATE_BUCKET_NAME }}
  ECR_REPO:        ${{ secrets.ECR_REPO_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build image and deploy ECS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.8

      - name: Init Terraform (infra)
        working-directory: ./infra
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ env.STATE_BUCKET }}" \
            -backend-config="key=infra/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Apply Terraform (infra)
        working-directory: ./infra
        run: |
          terraform apply -auto-approve

      - name: Get outputs from Infra
        id: infra_outputs
        working-directory: ./infra
        run: |
          echo "ecr_url=$(terraform output -raw ecr_repository_url)" >> $GITHUB_OUTPUT

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${{ steps.infra_outputs.outputs.ecr_url }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(date +%s)
          IMAGE_URI="${{ steps.infra_outputs.outputs.ecr_url }}:$IMAGE_TAG"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Init Terraform (ecs-service)
        working-directory: ./ecs-service
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ env.STATE_BUCKET }}" \
            -backend-config="key=ecs-service/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Plan ECS Service Update
        working-directory: ./ecs-service
        run: terraform plan -out=tfplan -var="image_url=${{ env.IMAGE_URI }}"

      - name: Apply ECS Service Update
        working-directory: ./ecs-service
        run: terraform apply -auto-approve tfplan
