name: Phase 1 Infra Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: environments/dev/phase1
        run: terraform init

      - name: Terraform Plan
        working-directory: environments/dev/phase1
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: environments/dev/phase1
        run: terraform apply -auto-approve tfplan
